Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -5,6 +5,8 @@ steps:
   args: 
     - '-c'
     - |
+      set -e
+
       echo ""
       echo "*************************************************************************"
       echo "** Checking out '$_BASE_BRANCH' branch ..."
@@ -24,24 +26,41 @@ steps:
 
       echo ""
       echo "***************************************************************************************************************"
-      echo "** Updating Merge Request 'projects/$CI_MERGE_REQUEST_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID' ..."
-      echo "***************************************************************************************************************"          
-      PR_URL="https://api.github.com/repos/fernandorubbo/costimator-github/issues/$_PR_NUMBER"
+      echo "** Updating Pull Request '$_PR_NUMBER' ..."
+      echo "***************************************************************************************************************" 
+      createObject() {
+        url=$$1
+        body=$$2
+        resp=$(curl -w "\nSTATUS_CODE:%{http_code}\n" -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $_GITHUB_TOKEN" -d "$$body"  $$url)
+        httpStatusCode=$([[ $$resp =~ [[:space:]]*STATUS_CODE:([0-9]{3}) ]] && echo $${BASH_REMATCH[1]})
+        if [ $$httpStatusCode != "201" ] 
+          then
+            echo "Error creating object!"
+            echo "\- URL: $$url "
+            echo "\- BODY: $$body "
+            echo "\- RESPONSE: $$resp "
+            exit -1
+        fi
+      }
 
-      curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $_GITHUB_TOKEN" -d "$(cat output.json)" "$PR_URL/comments"
-      
+      comments_url="https://api.github.com/repos/fernandorubbo/costimator-github/issues/$_PR_NUMBER/comments"
+      comments_body="$(cat output.json)"
+      createObject $$comments_url "$$comments_body"
+
       COST_USD_THRESHOLD=10
       POSSIBLY_COST_INCREASE=$(cat output.diff | jq ".summary.maxDiff.usd")
-      if (( $(echo "$POSSIBLY_COST_INCREASE > $COST_USD_THRESHOLD" | bc -l) ))
+      if (( $(echo "$$POSSIBLY_COST_INCREASE > $$COST_USD_THRESHOLD" | bc -l) ))
         then
           echo ""
           echo "****************************************************************************************"
-          echo "** Possible cost increase bigger than \$$COST_USD_THRESHOLD USD detected. Requesting FinOps approval ..."
-          echo "****************************************************************************************"    
-          curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: Bearer $_GITHUB_TOKEN" -d "{\"reviewers\":[\"$_GITHUB_FINOPS_REVIEWER_ID\"]}"  "$PR_URL/requested_reviewers"
+          echo "** Possible cost increase bigger than \$ $$COST_USD_THRESHOLD USD detected. Requesting FinOps approval ..."
+          echo "****************************************************************************************"   
+          reviewers_url="https://api.github.com/repos/fernandorubbo/costimator-github/pulls/$_PR_NUMBER/requested_reviewers"
+          reviewers_body="{\"reviewers\":[\"$_GITHUB_FINOPS_REVIEWER_ID\"]}"
+          createObject $$reviewers_url "$$reviewers_body"
         else
           echo ""
           echo "****************************************************************************************************************"
-          echo "** No cost increase bigger than \$$COST_USD_THRESHOLD USD detected. FinOps approval is NOT required in this situation!"
+          echo "** No cost increase bigger than \$ $$COST_USD_THRESHOLD USD detected. FinOps approval is NOT required in this situation!"
           echo "****************************************************************************************************************"
       fi
